version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/website/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
